### ISSUE TITLE
Missing chat template for Hugging Face Agents

### ISSUE THREAD

**Issue by justinphan3110cais** [skywalker023/confAIde#1]
Hi author, 

I found that it is missing chat template for the Hugging Face Agents class, which makes it not comparable to querying API models with a chat template (GPT, togetherAPI). Therefore, were the experiments in the paper conducted with or without the chat template for Llama2-chat and mixtral?

**Comment by skywalker023** [comment]
Hello, Justin
Thanks for the question! We used TogetherAI for running Mixtral and Llama-2!
